// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: proto/cyberscope.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinuxLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SourceIp      string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProcessName   string                 `protobuf:"bytes,4,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinuxLogRequest) Reset() {
	*x = LinuxLogRequest{}
	mi := &file_proto_cyberscope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinuxLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinuxLogRequest) ProtoMessage() {}

func (x *LinuxLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberscope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinuxLogRequest.ProtoReflect.Descriptor instead.
func (*LinuxLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_cyberscope_proto_rawDescGZIP(), []int{0}
}

func (x *LinuxLogRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LinuxLogRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *LinuxLogRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LinuxLogRequest) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_cyberscope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cyberscope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_cyberscope_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_cyberscope_proto protoreflect.FileDescriptor

const file_proto_cyberscope_proto_rawDesc = "" +
	"\n" +
	"\x16proto/cyberscope.proto\x12\x04logs\"\x8c\x01\n" +
	"\x0fLinuxLogRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12!\n" +
	"\fprocess_name\x18\x04 \x01(\tR\vprocessName\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2I\n" +
	"\n" +
	"LogService\x12;\n" +
	"\fSendLinuxLog\x12\x15.logs.LinuxLogRequest\x1a\x14.logs.StatusResponseB\x1cZ\x1assh-log-monitor/proto;logsb\x06proto3"

var (
	file_proto_cyberscope_proto_rawDescOnce sync.Once
	file_proto_cyberscope_proto_rawDescData []byte
)

func file_proto_cyberscope_proto_rawDescGZIP() []byte {
	file_proto_cyberscope_proto_rawDescOnce.Do(func() {
		file_proto_cyberscope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cyberscope_proto_rawDesc), len(file_proto_cyberscope_proto_rawDesc)))
	})
	return file_proto_cyberscope_proto_rawDescData
}

var file_proto_cyberscope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cyberscope_proto_goTypes = []any{
	(*LinuxLogRequest)(nil), // 0: logs.LinuxLogRequest
	(*StatusResponse)(nil),  // 1: logs.StatusResponse
}
var file_proto_cyberscope_proto_depIdxs = []int32{
	0, // 0: logs.LogService.SendLinuxLog:input_type -> logs.LinuxLogRequest
	1, // 1: logs.LogService.SendLinuxLog:output_type -> logs.StatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cyberscope_proto_init() }
func file_proto_cyberscope_proto_init() {
	if File_proto_cyberscope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cyberscope_proto_rawDesc), len(file_proto_cyberscope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cyberscope_proto_goTypes,
		DependencyIndexes: file_proto_cyberscope_proto_depIdxs,
		MessageInfos:      file_proto_cyberscope_proto_msgTypes,
	}.Build()
	File_proto_cyberscope_proto = out.File
	file_proto_cyberscope_proto_goTypes = nil
	file_proto_cyberscope_proto_depIdxs = nil
}
