// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/logs.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_TCP PacketType = 0
	PacketType_UDP PacketType = 1
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "TCP",
		1: "UDP",
	}
	PacketType_value = map[string]int32{
		"TCP": 0,
		"UDP": 1,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logs_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_proto_logs_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{0}
}

type LogRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SourceIp        string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DestinationIp   string                 `protobuf:"bytes,3,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	SourcePort      int32                  `protobuf:"varint,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestinationPort int32                  `protobuf:"varint,5,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Size            int32                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Timestamp       string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type            PacketType             `protobuf:"varint,8,opt,name=type,proto3,enum=logs.PacketType" json:"type,omitempty"`
	ProcessId       int32                  `protobuf:"varint,9,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ProcessName     string                 `protobuf:"bytes,10,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ExecutablePath  string                 `protobuf:"bytes,11,opt,name=executable_path,json=executablePath,proto3" json:"executable_path,omitempty"`
	FileHash        string                 `protobuf:"bytes,12,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_proto_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LogRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *LogRequest) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *LogRequest) GetSourcePort() int32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *LogRequest) GetDestinationPort() int32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *LogRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LogRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogRequest) GetType() PacketType {
	if x != nil {
		return x.Type
	}
	return PacketType_TCP
}

func (x *LogRequest) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *LogRequest) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *LogRequest) GetExecutablePath() string {
	if x != nil {
		return x.ExecutablePath
	}
	return ""
}

func (x *LogRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_logs_proto protoreflect.FileDescriptor

const file_proto_logs_proto_rawDesc = "" +
	"\n" +
	"\x10proto/logs.proto\x12\x04logs\"\x99\x03\n" +
	"\n" +
	"LogRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12%\n" +
	"\x0edestination_ip\x18\x03 \x01(\tR\rdestinationIp\x12\x1f\n" +
	"\vsource_port\x18\x04 \x01(\x05R\n" +
	"sourcePort\x12)\n" +
	"\x10destination_port\x18\x05 \x01(\x05R\x0fdestinationPort\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x05R\x04size\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\x12$\n" +
	"\x04type\x18\b \x01(\x0e2\x10.logs.PacketTypeR\x04type\x12\x1d\n" +
	"\n" +
	"process_id\x18\t \x01(\x05R\tprocessId\x12!\n" +
	"\fprocess_name\x18\n" +
	" \x01(\tR\vprocessName\x12'\n" +
	"\x0fexecutable_path\x18\v \x01(\tR\x0eexecutablePath\x12\x1b\n" +
	"\tfile_hash\x18\f \x01(\tR\bfileHash\"%\n" +
	"\vLogResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*\x1e\n" +
	"\n" +
	"PacketType\x12\a\n" +
	"\x03TCP\x10\x00\x12\a\n" +
	"\x03UDP\x10\x012<\n" +
	"\n" +
	"LogService\x12.\n" +
	"\aSendLog\x12\x10.logs.LogRequest\x1a\x11.logs.LogResponseB\x1cZ\x1assh-log-monitor/proto;logsb\x06proto3"

var (
	file_proto_logs_proto_rawDescOnce sync.Once
	file_proto_logs_proto_rawDescData []byte
)

func file_proto_logs_proto_rawDescGZIP() []byte {
	file_proto_logs_proto_rawDescOnce.Do(func() {
		file_proto_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logs_proto_rawDesc), len(file_proto_logs_proto_rawDesc)))
	})
	return file_proto_logs_proto_rawDescData
}

var file_proto_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logs_proto_goTypes = []any{
	(PacketType)(0),     // 0: logs.PacketType
	(*LogRequest)(nil),  // 1: logs.LogRequest
	(*LogResponse)(nil), // 2: logs.LogResponse
}
var file_proto_logs_proto_depIdxs = []int32{
	0, // 0: logs.LogRequest.type:type_name -> logs.PacketType
	1, // 1: logs.LogService.SendLog:input_type -> logs.LogRequest
	2, // 2: logs.LogService.SendLog:output_type -> logs.LogResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_logs_proto_init() }
func file_proto_logs_proto_init() {
	if File_proto_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logs_proto_rawDesc), len(file_proto_logs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logs_proto_goTypes,
		DependencyIndexes: file_proto_logs_proto_depIdxs,
		EnumInfos:         file_proto_logs_proto_enumTypes,
		MessageInfos:      file_proto_logs_proto_msgTypes,
	}.Build()
	File_proto_logs_proto = out.File
	file_proto_logs_proto_goTypes = nil
	file_proto_logs_proto_depIdxs = nil
}
